# Generated by Django 4.2.5 on 2023-09-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("prod_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Food", "Food"),
                            ("Book", "Book"),
                        ],
                        default="...",
                        max_length=15,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
